RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:    
	.string "Ma meuf et moi, nous cherchons une\n"
	.string "nouvelle série à regarder sur Netflix.\p"
	.string "Y'a Invincible, Attack des Titans,\n"
	.string "Stranger Things…\p"
	.string "Wesh, y'a trop de choix !$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "J'avais prévu de sortir avec mes amies,\n"
	.string "mais lui m'oblige à rester pour regarder\l"
	.string "Netflix…\p"
	.string "Honnêtement, pourquoi suis-je encore\n"
	.string "avec lui…?$"

