gText_Birch_Welcome::
	.string "Salut à tous !\n"
	.string "Je suis le Professeur Fildrong !\p"
	.string "Je me retrouve devant cette caméra\n"
	.string "pour vous dire que je quitte ma putain\l"
	.string "de carrière de streamer pour devenir\l"
	.string "Chercheur Pokémon !\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Les Pokémon vivent en harmonie avec\n"
	.string "les humains depuis plusieurs années.\p"
	.string "Mais vu que vous n'êtes pas des noobs,\n"
	.string "vous connaissez déjà toute l'histoire !\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ce truc…\n"
	.string "Eh bien…!\p"
	.string "Psst…!\n"
	.string "Ce n'est pas ce qui était convenu !\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Ah…\n"
	.string "Ok, on va faire avec…!\p"
	.string "Mesdames et messieurs, ceci est une\n"
	.string "toute nouvelle espèce de Pokémon !\p"
	.string "Il est spécial certes mais c'est bel et\n"
	.string "bien un Pokémon parmi tant d'autres !\p"
	.string "Pas convaincu ?\p"
	.string "Bon bah, tant pis…!\n"
	.string "Bref, changement de programme !\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Oui, toi là-bas !\n"
	.string "Qui es-tu ?!$"

gText_Birch_BoyOrGirl::
	.string "Un mec ?\n"
	.string "Ou une meuf ?$"

gText_Birch_WhatsYourName::
	.string "Quel est ton nom ?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN} ?$"

gText_Birch_YourePlayer::
	.string "D'accord machin !\p"
	.string "Désormais tu seras le protagoniste\n"
	.string "de cette nouvelle aventure palpitante\l"
	.string "et inoubliable.\p"
	.string "Demain, je prévois de retourné dans\n"
	.string "mon laboratoire à Bourg Paumé.\p"
	.string "Alors si tu veux un Pokémon, ne sois\n"
	.string "pas en retard !\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "En attendant vous autres, je vais\n"
	.string "devoir vous laisser et je vous dis,\l"
	.string "à la prochaine !\p"
	.string "TCHOUSS !!\p"
	.string "$"
