gText_Birch_Welcome::
	.string "Salut à tous ! Je suis le Professeur\n"
	.string "Fildrong.\p"
	.string "Je me retrouve devant cette caméra\n"
	.string "pour vous dire que je quitte ma putain\l"
	.string "de carrière de streameur et devenir\l"
	.string "Chercheur Pokémon !\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Les Pokémon vivent en harmonie avec\n"
	.string "les humains depuis plusieurs années.\p"
	.string "Mais vu que vous n'êtes pas des noobs,\n"
	.string "vous connaissez déjà toute l'histoire !\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ce petit… Truc… Et bien heu…\p"
	.string "C'est un Pokémon voyons !\p"
	.string "Oui bon ! Ce truc ressemble à une\n"
	.string "tasse de café…\p"
	.string "Mais attention !\p"
	.string "C'est une tasse de café, avec des\n"
	.string "pieds !\p"
	.string "C'est assez spécial, on va dire…\p"
	.string "Cependant, ça reste quand même un\n"
	.string "Pokémon !\p"
	.string "Pas convaincu ?\p"
	.string "Oh ok…!\p"
	.string "Heu… Changement de sujet !\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Oui, toi là-bas ! Es-tu…$"

gText_Birch_BoyOrGirl::
	.string "Un mec ?\n"
	.string "Ou une meuf ?$"

gText_Birch_WhatsYourName::
	.string "Quel est ton nom ?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN} ?$"

gText_Birch_YourePlayer::
	.string "D'accord machin !\p"
	.string "Désormais tu seras le protagoniste\n"
	.string "de cette nouvelle aventure palpitante\l"
	.string "et inoubliable.\p"
	.string "Demain, je prévois d'aller dans mon\n"
	.string "nouveau laboratoire à Bourg Paumé.\p"
	.string "Alors si tu veux un Pokémon, ne sois\n"
	.string "pas en retard !\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "En attendant vous autres, je vais\n"
	.string "devoir vous laisser et je vous dis\l"
	.string "à la prochaine !\p"
	.string "Tchouss !\p"
	.string "$"
