gText_Birch_Welcome::
	.string "Salut à tous !\p"
	.string "C'est Fildrong et aujourd'hui je\n"
	.string "tiens à vous dire que je quitte\l"
	.string "ma putain de carrière de vidéaste\l"
	.string "pour devenir Chercheur Pokémon.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Je vous présente un Pokémon qui\n"
	.string "est très très fun pour commencer!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Euh… attends…\p"
	.string "Qu'est-ce c'est que cette merde ?!\p"
	.string "Ce n'est pas ce qui était convenu !\p"
	.string "Ah…\p"
	.string "Pas de mot vulgaire pour garder la\n"
	.string "monétisation…?\p"
	.string "Oh ok…\p"
	.string "C'est pas ce que j'allais dire hein…\n"
	.string "Mais bon…\p"
	.string "Changement de programme !!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Eh toi là-bas !! Es-tu…$"

gText_Birch_BoyOrGirl::
	.string "Un mec ?\n"
	.string "Ou une meuf ?$"

gText_Birch_WhatsYourName::
	.string "Quel est ton nom ?!$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN} ?$"

gText_Birch_YourePlayer::
	.string "D'accord {PLAYER}{KUN}.\p"
	.string "Je serai dans mon labo demain matin à\n"
	.string "Bourg Paumé. Ne sois pas en retard.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Désormais tu seras le protagoniste\n"
	.string "de cette nouvelle aventure palpitante\l"
	.string "et inoubliable.\p"
	.string "En attendant, vous autres je vais\n"
	.string "devoir vous laisser et je vous dis,\l"
	.string "à la prochaine !\p"
	.string "TCHOUSS !\p"
	.string "$"
