Text_PictureBookShelf:
	.string "Ce sont des albums de Pokémon.$"

Text_BookShelf:
	.string "Il y a toutes sortes de livres.$"

Text_PokemonCenterBookShelf:
	.string "Des magazines érotiques…\n"
	.string "Des mangas…\p"
	.string "Des romans Pokémon…\n"
	.string "Des catalogues…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "C'est vide.$"

Text_ShopShelf:
	.string "Les étagères regorgent de toutes\n"
	.string "sortes de produits Pokémon.$"

Text_Blueprint:
	.string "Voilà un curieux plan !\n"
	.string "Ça a l'air compliqué.$"
