	.align 2
gText_ConfirmSave::
	.string "Voulez-vous sauvegarder la partie ?$"

gText_AlreadySavedFile::
	.string "Il y a déjà une partie sauvegardée.\n"
	.string "Voulez-vous l'écraser ?$"

gText_SavingDontTurnOff::
	.string "Sauvegarde en cours…\n"
	.string "N'éteignez pas la console.$"

gText_PlayerSavedGame::
	.string "{PLAYER} a sauvegardé la partie.$"

gText_DifferentSaveFile::
	.string "Attention !\p"
	.string "Une partie différente est déjà\n"
	.string "sauvegardée.\p"
	.string "Voulez-vous la remplacer ?$"

gText_SaveError::
	.string "Erreur de sauvegarde.\p"
	.string "Changer la mémoire de sauvegarde.$"

gText_SavingDontTurnOffPower::
	.string "Sauvegarde en cours…\n"
	.string "Ne pas éteindre.$"
