OldaleTown_House2_MapScripts::
	.byte 0

Fourqueue_House2_EventScript_SchoolKidBoy1::
	msgbox Fourqueue_House2_Text_SchoolKidBoy1, MSGBOX_NPC
	end

Fourqueue_House2_EventScript_SchoolKidBoy2::
	msgbox Fourqueue_House2_Text_SchoolKidBoy2, MSGBOX_NPC
	end

Fourqueue_House2_Text_SchoolKidBoy1:
	.string "Désolé mais tu es tellement bête que\n"
	.string "rien que le fait de parler avec toi\l"
	.string "me rabaisse.$"

Fourqueue_House2_Text_SchoolKidBoy2:
	.string "Tu connais Risimon ?\p"
	.string "Pas étonnant vu que cette merde a\n"
	.string "flop sur Steam !$"

